name: pkg-build-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build:production
      - run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: actions/download-artifact@v3
      - run: ls -la
      # - env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm publish
      #   with:
      #     name: ot-build
